#!/usr/bin/env python3

def generate_test_shader(mask):
    shader = '// Autogenerated by generate_rt_mask.py\n'
    shader += 'cbuffer Data : register(b0) { float v0, v1, v2, v3, v4, v5, v6, v7; };\n'
    shader += 'struct PSOut {\n'
    for i in range(8):
        if (mask & (1 << i)) != 0:
            shader += f'  float c{i} : SV_Target{i};\n'
    shader += '};\n\n'

    shader += 'PSOut main() {\n'
    shader += '  PSOut o;\n'
    for i in range(8):
        if (mask & (1 << i)) != 0:
            shader += f'  o.c{i} = v{i};\n'
    shader += '  return o;\n'
    shader += '}\n'

    with open(f'rt_mask_{mask}.ps_5_0.hlsl', 'w') as f:
        f.write(shader)

def main():
    combined = '// Autogenerated by generate_rt_mask.py\n'
    combined += '#pragma once\n'
    for i in range(256):
        combined += f'#include "rt_mask_{i}.h"\n'
    combined += 'static const D3D12_SHADER_BYTECODE *rt_masks[] = {\n'

    for i in range(256):
        generate_test_shader(i)
        combined += f'  &rt_mask_{i}_dxbc,\n'

    combined += '};\n'

    with open('headers/rt_mask_combined.h', 'w') as f:
        f.write(combined)

if __name__ == '__main__':
    main()
