// Autogenerated by generate_rt_mask.py
cbuffer Data : register(b0) { float v0, v1, v2, v3, v4, v5, v6, v7; };
struct PSOut {
  float c5 : SV_Target5;
  float c7 : SV_Target7;
};

PSOut main() {
  PSOut o;
  o.c5 = v5;
  o.c7 = v7;
  return o;
}
