// Autogenerated by generate_rt_mask.py
cbuffer Data : register(b0) { float v0, v1, v2, v3, v4, v5, v6, v7; };
struct PSOut {
  float c6 : SV_Target6;
};

PSOut main() {
  PSOut o;
  o.c6 = v6;
  return o;
}
