// Autogenerated by generate_rt_mask.py
cbuffer Data : register(b0) { float v0, v1, v2, v3, v4, v5, v6, v7; };
struct PSOut {
  float c0 : SV_Target0;
  float c2 : SV_Target2;
  float c4 : SV_Target4;
  float c6 : SV_Target6;
};

PSOut main() {
  PSOut o;
  o.c0 = v0;
  o.c2 = v2;
  o.c4 = v4;
  o.c6 = v6;
  return o;
}
