// Autogenerated by generate_rt_mask.py
cbuffer Data : register(b0) { float v0, v1, v2, v3, v4, v5, v6, v7; };
struct PSOut {
  float c3 : SV_Target3;
  float c4 : SV_Target4;
};

PSOut main() {
  PSOut o;
  o.c3 = v3;
  o.c4 = v4;
  return o;
}
