#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Regenerate the embedded shader; DXC is only needed when changing its source."""

import argparse
from pathlib import Path
import struct
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dxc", default="dxc")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    directory = Path(__file__).resolve().parent
    with tempfile.TemporaryDirectory() as temporary:
        binary = Path(temporary) / "shader.dxil"
        subprocess.run([
            args.dxc, "-T", "cs_6_0", "-E", "TrailSort_CS", "-O3", "-WX",
            str(directory / "first_light_trailsort.hlsl"), "-Fo", str(binary),
        ], check=True)
        data = binary.read_bytes()
    words = struct.unpack("<" + "I" * (len(data) // 4), data)
    text = (
        "/* Generated by compile_first_light_trailsort.py with DXC v1.8.2505.1.\n"
        " * Source: first_light_trailsort.hlsl (LGPL-2.1-or-later). */\n"
        "static const uint32_t first_light_trailsort_dxil[] =\n{\n"
    )
    for offset in range(0, len(words), 8):
        text += "    " + ", ".join(f"0x{word:08x}" for word in words[offset:offset + 8]) + ",\n"
    text += "};\n"
    header = directory / "first_light_trailsort.h"
    if args.check:
        if header.read_text() != text:
            raise SystemExit("Generated shader header differs from the checked-in version")
        print("Shader header matches the HLSL source")
    else:
        header.write_text(text)


if __name__ == "__main__":
    main()
