#version 450
layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0) uniform sampler2D Tex;
layout(set = 0, binding = 1) writeonly uniform image2D SwapChain;

layout(push_constant) uniform Registers
{
  vec2 inv_resolution;
};

void main()
{
  ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
  vec2 uv = (vec2(coord) + 0.5) * inv_resolution;
  imageStore(SwapChain, coord, textureLod(Tex, uv, 0.0));
}
